### PR TITLE
Add bracket select and replace

### LINKED ISSUE #280: Add command to select matching bracket
I would like to suggest a new functionality:

I am translating a code from MATLAB to JULIA

MATLAB uses ( ) to index arrays, while JULIA does use [ ]

What about a functionality that allows me to change one bracket for the other? 

For example I have

x(idx, :)

I put the cursor before the (  so that the ( is highlighted together with the )
I hit my magic shortcut, lets say Ctrl+Alt+C and hit [

Then atom automatically replaces the ( ) for [ ] and now my text is

x[idx, :]

### PR DESCRIPTION
**Pull request by VELIKII-DIVAN**
### Description of the Change
A new command to brackets pair selection when cursor is near one of bracket. After selection the pair can be replaced by another.

### Alternate Designs
None

### Benefits
New command `bracket-matcher:select-matching-brackets`
New behavior after this command

### Possible Drawbacks
There may be new bugs?

### Applicable Issues
Fixes #280

### CODE REVIEW

**Comment by zach-nervana** [comment]
@VELIKII-DIVAN I'm not sure entirely how it works, but #280 is fixed by this pull request, and that issue had a bounty on it of $50. I believe you should be able to claim the bounty here: https://www.bountysource.com/issues/43914367-add-command-to-select-matching-bracket

**Comment by ungb** [comment]
@VELIKII-DIVAN I just tested the new command and everything looks good!  If you get a chance, can you resolve the conflict in `spec/bracket-matcher-spec.coffee`? 

This will be good to merge afterwards!

**Comment by ungb** [comment]
thanks @VELIKII-DIVAN for this PR!  I've resolved the merge conflicts and did some sanity check on the changes!

**Comment by ungb** [comment]
@VELIKII-DIVAN after speaking with the team, I had to remove the keymaps for this in https://github.com/atom/bracket-matcher/commit/854444ecc9e4332145267648f352847b199fe5e2 since it will add conflicts to other keymaps from other packages. The users can easily add their own keymaps by adding the following to their `keymap.cson`:


```cson

'atom-text-editor':
  'ctrl-alt-c': 'bracket-matcher:select-matching-brackets'


```

**Pull request merged**
