### PR TITLE
Fixes reverse brace/bracket matching

### LINKED ISSUE #116: Improve brace matching
_From @mindplay-dk on March 15, 2015 14:10_

Brace matching in ATOM is like this:

image

In e.g. Php Storm, brace matching prioritizes parens based on their direction - like this:

image

Why this is better: because, regardless of whether the cursor is over an opening or closing brace, it's matched in such a way that you're typing _outside_ the matching parens - consistently.

The way it works in ATOM currently, if I start typing in the first example, I'm typing on the outside of the matched parens - but if I start typing in the second example, I'm typing inside the matched parens. 

Having to cursor right before you start typing after a closing brace, and then having the "wrong" parens highlight when you do, is really confusing.

_Copied from original issue: atom/atom#5973_

### PR DESCRIPTION
**Pull request by dmohs**
Fixes #116

Before | After
------------ | -------------
screen shot 2016-12-12 at 1 04 06 am Cursor before closing bracket | screen shot 2016-12-12 at 1 04 24 am Behavior is unchanged
screen shot 2016-12-12 at 1 13 20 am Cursor after closing bracket | screen shot 2016-12-12 at 1 04 56 am Highlights inner set of brackets

### CODE REVIEW

**Comment by dmohs** [comment]
I know I have some work to do here with respect to tests and style, but before I polish I'd love feedback on whether this seems reasonable.

**Comment by 50Wliu** [comment]
I don't see any particular problems with this approach.  It would be nice if you could upload before/after screenshots.

**Comment by dmohs** [comment]
That is a great suggestion! Comment edited.

**Comment by dmohs** [comment]
Do you think `isInverse` would be clearer if it were called `reverse` or `reverseDirection`?

**Comment by 50Wliu** [comment]
I think `isInverse` fits the role well, since we're matching the inverse of the other bracket.

**Comment by dmohs** [comment]
@50Wliu Anything I can do to make this more enticing for a reviewer?

**Comment by 50Wliu** [comment]
We have a backlog of PRs, so reviewing takes time.  To answer your question though, no, there's nothing else you need to do.

**Comment by dmohs** [comment]
@50Wliu Sounds good I will be patient. Thank you so much for walking me through this.

**Comment by dmohs** [comment]
I've been using this modified version of the plugin to edit ClojureScript code since December. While I'm not sure it's perfect, it makes a monumental difference. Given the importance of parentheses in any Lisp, it was hard to use Atom without it.

**Comment by 50Wliu** [comment]
I would appreciate an extra test specifically asserting that the inner set of brackets is always highlighted.  Looks like you could use [this line](https://github.com/atom/bracket-matcher/blob/fd86874edc9fde83f01adb71e56acd1101782b6f/spec/fixtures/sample.js#L9) in the fixtures file.

**Comment by dmohs** [comment]
Thanks @50Wliu. I'd like this to be bulletproof, so happy to add tests. I'll look into it.

**Comment by dmohs** [comment]
@50Wliu Added tests for multiple brackets, both opening and closing.

**Comment by dmohs** [comment]
@50Wliu I could use a hand understanding what went wrong with the Travis build. It looks like another PR (not mine) failed for the same reason.

**Comment by rsese** [comment]
@dmohs just a heads up that @50Wliu is out till next week I believe.

**Comment by 50Wliu** [comment]
Merge from latest master.  The CI update should fix it.

**Comment by dmohs** [comment]
@50Wliu Thanks that did it!

**Comment by 50Wliu** [comment]
This looks good to me.
/cc @atom/feedback for comments.

**Comment by lee-dohm** [comment]
Thanks for your perseverance @dmohs! Great work :tada:

**Comment by dmohs** [comment]
Thank you so much @lee-dohm. And thank you @50Wliu for the consistent help throughout.

**Pull request merged**
