### PR TITLE
Expand selection on repeated calls to bracket-matcher:select-inside-brackets.

### PR DESCRIPTION
**Pull request by bwinton**
Fixes issue #74.

### CODE REVIEW

**Comment by cortner** [comment]
Would love to have this s. I hope it can be merged

**Comment by 50Wliu** [comment]
At a glance this would need specs to be considered.

**Comment by Radivarig** [comment]
Any update on this?

**Comment by revelt** [comment]
We solved selection inside the tags, now it's time to implement this expansion. Team, let's get this feature released! If we'll implement this, Atom will surpass the Sublime for HTML development. We'll be able to grab/copy/paste/delete template parts easily.

**Comment by bwinton** [comment]
(I actually switched to VSCode, so I'm not really working on this anymore, if someone wants to take it over and try to get it landed, then please feel free… 🙂)

**Comment by revelt** [comment]
@bwinton off-topic, but do you feel fine conscience-wise supporting M$ by using its products? I mean whole OS conceptually was a mean to counter M$ and its products...

**Comment by bwinton** [comment]
@revelt You're right, it's off-topic. Email me at bwinton@latte.ca, and I'll be happy to chat about it. 🙂

**Comment by 50Wliu** [comment]
@revelt a good first step would be to fix the merge conflicts and open a new PR!

**Comment by revelt** [comment]
I never coded in cofeescript, I wouldn't be able to chip in here :( If it was in normal JS I'd give a shot but this – no.. Sorry :o)

**Comment by zoheb391** [comment]
@revelt the emmet package solves this issue well if you need an alternative (cmd-d to select inside tags) (cmd-shift-d includes tags)

**Comment by revelt** [comment]
@zoheb391 thank you, I wasn't aware of that. HTML-wise, I'm mainly coding email so Emmet's snippets are not usually suitable (I prep my own snippets, and use Dash for that); I haven't got this plugin active atm. I'll check it out. But Atom's feature would be awesome nonetheless!!!

**Pull request closed without merging**
