### PR TITLE
Fix performance regression when there is no >

### LINKED ISSUE #314: Bracket Matcher freezes editor if running bracket-matcher:select-inside-brackets on a comment
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Bracket Matcher freezes editor if running bracket-matcher:select-inside-brackets on a comment

⚡️ 👍 to @Ben3eeE for finding this
### Steps to Reproduce

1. clone bracket-matcher 
2. checkout master branch
3. `apm install && apm link` bracket matcher
4. Open bracket-matcher repo in atom 
5. go to line 88 of tag-finder.coffee
6. move your cursor to `<` in comment
7. run 'bracket-matcher:select-inside-brackets'
8. Atom will hang

**Expected behavior:** [What you expect to happen]
Should load up atom quickly and work
**Actual behavior:** [What actually happens]
Atom freezes up.  

___NOTE: 
Looks like this is caused by https://github.com/atom/bracket-matcher/pull/304 ___

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
```
Atom    : 1.21.0-dev-3988ca2b9
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0


```

This is related to the change in https://github.com/atom/bracket-matcher/pull/304 

### Additional Information

/cc: @atom/feedback 

**NOTE** These changes are not in atom/atom master yet, but exist on master branch of bracket-matcher.  @50Wliu is working on a fix currently, please don't publish or update version of bracket matcher until fix is in.

### PR DESCRIPTION
**Pull request by 50Wliu**
WIP

This works, but I'm not sure if it introduces other regressions (unlikely, but I'm not the one to say :blush:).  It would also be nice to change this to use scopes instead of using word boundaries to find tag boundaries.

Fixes #314

### CODE REVIEW

**Comment by 50Wliu** [comment]
Darn.  There's still some catastrophic backtracking, even with this new regex.

**Comment by 50Wliu** [comment]
Ok, I believe this should fix things.  One downside: multiline self-closing tags are not recognized as self-closing tags.

**Comment by Ben3eeE** [comment]
@50Wliu Do you think we can ship this even with the issue of multiline self-closing tags?

**Comment by 50Wliu** [comment]
Since the self-closing tags highlighting isn't even on atom/atom master yet, I think it's safe to merge this and create another followup issue about multiline self-closing tags.

**Comment by Ben3eeE** [comment]
@ungb I have tested this for a while and it looks good to me. I added it to your TODO. Can you merge this after you have tested it?

**Comment by ungb** [comment]
I've tested this as well. Merging! thanks @50Wliu and @Ben3eeE for taking this on!

**Pull request merged**
